### ISSUE TITLE
WV icon?

### ISSUE THREAD

**Issue by rgleason** [jongough/windvane_pi#28]
Jon, in reviewing all the plugins and checking basic operations IE being able to click on the toolbar icon to open and to close and making sure that they all don't crash OpenCPN when disabled or from some preferences actions... I noticed a couple of things.

1. Windvane works well, once the question is answered. (which I think is fine)
2. For overall look and consistency across all the plugins, the windvane icons could be improved. 
- I understand this is completely up to the plugin developer....
- Generally the colored icons are being used for the builtin plugins and black and white for the external.
- Toolbar icons generally use the dark field 80% gray background  and have light gray drawing or Alphanumerics.
- Listing panel icons generally use a light 10% grey background to match the listing field and then darker characters and drawing.
3. Do you think we could have an icon "WV" or wind logo with these characteristics?

I think the plugin tools would look much better this way.

**Comment by rgleason** [comment]
It didn't take too long to make some icons...

windvane  - background is the same as the Toolbar. You could make the letters a little bigger I think. AP in lower right. Perhaps AP could be bigger.
![windvane](https://user-images.githubusercontent.com/2363959/142730442-5bc9ec15-9fb6-462c-b20d-d4f2cd7198a9.png)
[windvane.svg.txt](https://github.com/jongough/windvane_pi/files/7574687/windvane.svg.txt)

windvane_toggled  - letters are whiter to indicate toggled
![windvane_toggled](https://user-images.githubusercontent.com/2363959/142730451-d62ff9da-0501-4fea-877d-4cfc716d1d2c.png)
[windvane_toggled.svg.txt](https://github.com/jongough/windvane_pi/files/7574688/windvane_toggled.svg.txt)


LIsting - Panel Icon  for the Plugin Manager Icon, background is the same as the listing background.
![windvane_panel](https://user-images.githubusercontent.com/2363959/142730475-2964ffb0-2ca3-4b2a-b127-7be78e001718.png)
[windvane_panel.svg.txt](https://github.com/jongough/windvane_pi/files/7574689/windvane_panel.svg.txt)

**Comment by rgleason** [comment]
I redid ir. Remove the ".txt" and you have the svg.

windvane.svg

![windvane](https://user-images.githubusercontent.com/2363959/142731669-6a6d949c-9e09-4b8b-b2fd-e6f275f18a1f.png)

[windvane.svg.txt](https://github.com/jongough/windvane_pi/files/7574727/windvane.svg.txt)

windvane_toggled.svg   Letters are lighter for toggle.

![windvane_toggled](https://user-images.githubusercontent.com/2363959/142731772-cfb17df8-e479-4478-9034-2e45ae820a13.png)

[windvane_toggled.svg.txt](https://github.com/jongough/windvane_pi/files/7574728/windvane_toggled.svg.txt)

windvane_panel.svg  light background and black letters.

![windvane_panel](https://user-images.githubusercontent.com/2363959/142731488-c926fbad-87a2-42b0-9521-813262d29e06.png)
[windvane_panel.svg.txt](https://github.com/jongough/windvane_pi/files/7574732/windvane_panel.svg.txt)

**Comment by jongough** [comment]
This should be fixed by 1.0.26.0

**Comment by rgleason** [comment]
OK, I'll close.  I still have 1.0.24.0 after update.
Found it in beta https://cloudsmith.io/~opencpn/repos/windvane-beta/packages/
Installed.
That fixed it.  Thanks
